"""Source-bound rule extraction. Does not implement, freeze or enable an evaluator."""
import hashlib,json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
SOURCE=ROOT/'state/frank-wallet-watch.md'
JSON=ROOT/'local-agent/config/frank_local_signal_v1.json'
MARKDOWN=ROOT/'meme/FRANK_LOCAL_SIGNAL_V1_POLICY.md'

def render(policy):
    lines=['# FRANK_LOCAL_SIGNAL_V1 — canonical rule extraction','',
           '**Policy status: FROZEN. Runtime activation requires separate successful acceptance and cutover.**','',
           'DERIVED_FROM_EXISTING_FRANK_BEHAVIOR_MODEL',
           'NON_BEHAVIOR_VETO_GATES_REMOVED_BY_USER_REQUIREMENT','',
           f"Canonical source: `{policy['source']['path']}` at commit `{policy['source']['commit']}`.",
           f"Source SHA256: `{policy['source']['sha256']}`.",'',
           'PRECONFIRM has Path S and Path C only. PRECONFIRM Path A/B do not exist. Persistence Path A/B belong to the later conviction stage.','',
           'Canonical Path C is mixed: single >=15,000 USD equivalent OR >=2 buys totaling >=25,000 USD equivalent in 60 minutes. The user explicitly selected only its repeated-buy branch for V1. PATH_C_SINGLE_LARGE_BUY = NOT_ACCUMULATION; provenance is preserved and no new user-visible signal is created.','',
           '## Extracted predicates','']
    for group in policy['groups']:
        lines.extend(['### '+group['name'],'',group['relationship'],'','| ID | Canonical source line | Categories | V1 treatment | Exact source predicate |','|---|---:|---|---|---|'])
        for p in group['predicates']:
            text=p['text'].replace('|','\\|')
            lines.append(f"| {p['id']} | {p['line']} | {', '.join(p['categories'])} | {p['treatment']} | {text} |")
        lines.append('')
    lines.extend(['## Exact numerical inventory','', '| Parameter | Canonical value | Status |','|---|---|---|'])
    for n in policy['numbers']:lines.append('| '+ ' | '.join(n)+' |')
    lines.extend(['','## Mapping and freeze decision','',
                  'ACCUMULATION V1: >=2 distinct confirmed ACTIVE BUY signatures for the same person/mint observed sequence in an inclusive rolling 3,600-second window, whose raw USDC quote quantities total >=25,000. No single-buy branch. No social, price, liquidity, GPT or HFT veto is added to this explicitly selected accumulation branch.',
                  'MULTIPLE V1: prior/current ACCUMULATION stage; T0 established by >=2 buys totaling >=3,000 USDC in <=3,600 seconds OR a >=5,000 USDC buy followed by another buy within 3,600 seconds; episode cumulative known USDC buys >=10,000; persistence A (WATCH in the prior hourly :29 observation) OR B (>=3 buys spanning >=2,700 seconds); known observed-sequence position >0 and >=50% episode peak OR positive net token buying in the last 3,600 seconds; no >35% token-unit drop in the last 3,600 seconds without fresh re-accumulation; no >=3 active swaps in <=60 seconds HFT episode; no proven rapid round-trip close within the old approximate 20-minute reference. If T0 age >10,800 seconds, require fresh active BUY within 3,600 seconds and an open position. No numeric extra ADD count, percentile, or lifetime-zero-start requirement is invented.',
                  'Social availability/calls, price suitability/chase limits, liquidity, executability, non-Frank token-control suitability and GPT vetoes do not participate in V1 pass/fail. WATCH remains silent; :29 is only the provenance-preserving persistence-A observation clock, not a delivery dependency. Signals and delivery run locally immediately.',
                  'USER_AUTHORIZED_UNIT_UPDATE: USDC quote => direct numeric comparison. The existing 3,000 / 5,000 / 10,000 numbers are preserved; accumulation uses the user-selected 25,000 USDC branch. Non-USDC quote without reliable conversion => amount gate UNDETERMINED; active trade, position and every non-amount predicate remain recorded. No independent dollar valuation or SOL-to-USD rule is claimed. Known USDC totals are conservative lower bounds when an episode also contains unvalued quote assets.',
                  'Canonical source has no numeric additional-ADD requirement, numeric dust/close threshold, required zero lifetime starting balance, or buy-size percentile. Missing definitions remain null in JSON.',
                  'Retained behavior candidates include exact active swaps, amount/count/window conditions, conviction persistence, retention/distribution, HFT behavior and hard on-chain exit conditions. Unquantified predicates are not guessed.',
                  'Historical replay is DRY_RUN_ONLY. It never dispatches notifications/Gmail. Each stage is emitted once per policy/person/mint/observed episode. Same-stage ADD updates state without duplicate delivery. An observed active-trade inventory of exactly zero closes the observed sequence; unresolvable sells preserve unknown inventory rather than guessing EXIT. LIFETIME_POSITION_UNKNOWN does not erase CURRENT_ACCUMULATION_SEQUENCE_KNOWN.',
                  'Test results, historical replay and controlled cutover evidence are reported separately; freezing this policy does not certify the runtime as live.',
                  'PRODUCTION TRADING = NO_GO; OTHER PERSONS = DEFERRED; NEW AUTOMATION = NO.',''])
    return '\n'.join(lines)

def extract():
    raw=SOURCE.read_bytes();source=raw.decode().splitlines()
    groups=[]
    def group(name,relation,rows):
        predicates=[]
        for number,categories,treatment in rows:
            predicates.append({'id':name.replace(' ','_')+'_'+str(number),'line':number,'text':source[number-1],'categories':categories.split(','),'treatment':treatment})
        groups.append({'name':name,'relationship':relation,'predicates':predicates})
    group('ACTIVE_SWAP_PROOF','All stages require proven active market exchange; passive activity does not count.',[(44,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(46,'OTHER','SOURCE_CONTEXT'),(47,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(48,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(49,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(50,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(51,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(52,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(53,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(55,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE')])
    group('HFT_EXECUTION','Global old no-alert filter; quantitative and unquantified execution patterns are preserved separately.',[(59,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(60,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE'),(61,'ONCHAIN_FRANK_BEHAVIOR,TIMING','UNQUANTIFIED_APPROXIMATE'),(62,'ONCHAIN_FRANK_BEHAVIOR','UNQUANTIFIED_PATTERN')])
    group('WATCH','Silent research state. All listed criteria apply; not a new accumulation threshold.',[(71,'ONCHAIN_FRANK_BEHAVIOR,TIMING','PERSISTENCE_A_CONTEXT'),(72,'ONCHAIN_FRANK_BEHAVIOR','PERSISTENCE_A_CONTEXT'),(73,'ONCHAIN_FRANK_BEHAVIOR','PERSISTENCE_A_CONTEXT'),(74,'ONCHAIN_FRANK_BEHAVIOR','PERSISTENCE_A_CONTEXT')])
    group('PRECONFIRM_PATH_S','((single >=5,000 USD) OR (rolling 60-minute aggregate >=10,000 USD)) AND first-party same-token call within prior 2 hours. Not authorized as the accumulation source.',[(277,'ONCHAIN_FRANK_BEHAVIOR,TIMING','NOT_MAPPED'),(278,'SOCIAL,TIMING','REMOVED_NON_BEHAVIOR_AUTHORITY'),(280,'SOCIAL','REMOVED_NON_BEHAVIOR_AUTHORITY')])
    group('PRECONFIRM_PATH_C','Social-unavailability fallback AND ((single active buy >=15,000 USD equivalent) OR (rolling 60-minute aggregate >=25,000 USD equivalent AND >=2 buys)). The single branch violates mandatory repeated-buy semantics.',[(283,'SOCIAL','REMOVED_NON_BEHAVIOR_AUTHORITY'),(284,'ONCHAIN_FRANK_BEHAVIOR','PATH_C_SINGLE_LARGE_BUY_NOT_ACCUMULATION_USER_EXCLUDED'),(285,'ONCHAIN_FRANK_BEHAVIOR,TIMING','USER_SELECTED_REPEATED_BRANCH_USDC_DIRECT')])
    group('PRECONFIRM_COMMON','Inherited preconfirm prerequisites and display rules, not additional buy thresholds.',[(274,'ONCHAIN_FRANK_BEHAVIOR,TIMING','OLD_HOURLY_DELIVERY_SUPERSEDED_TARGET_LOCAL'),(292,'PRICE','NO_PRICE_VETO_ALREADY_IN_OLD_STAGE'),(293,'PRICE','OPTIONAL_ENRICHMENT'),(294,'PRICE','OPTIONAL_ENRICHMENT'),(297,'OTHER','CANONICAL_TOKEN_IDENTITY_RETAIN'),(298,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(299,'LIQUIDITY','REMOVED_NON_BEHAVIOR_AUTHORITY'),(300,'OTHER','NOT_FRANK_BEHAVIOR_EXCLUDED_FROM_TARGET_AUTHORITY')])
    group('MEANINGFUL_ACCUMULATION_T0','OR of the two exact canonical paths; never anchor on an unqualified dust/probe.',[(190,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(193,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE'),(194,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE'),(196,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CONVICTION_CANDIDATE')])
    group('PERSISTENCE_PATH_A_B','A OR B. These are conviction persistence paths, not PRECONFIRM paths.',[(203,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE_PREVIOUS_HOURLY_WATCH'),(204,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE_45_MINUTES_3_BUYS')])
    group('FRESHNESS','Target latency is not itself a hard buy-count predicate. Beyond 3 hours, listed gates apply.',[(211,'TIMING','TARGET_NOT_NEW_HARD_THRESHOLD'),(212,'TIMING','RETAIN_CANDIDATE'),(214,'TIMING','RETAIN_CANDIDATE'),(215,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE'),(216,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE_UNQUANTIFIED_MATERIALITY'),(217,'PRICE,EXECUTABILITY','REMOVED_NON_BEHAVIOR_AUTHORITY'),(218,'OTHER,LIQUIDITY','REMOVE_NON_BEHAVIOR_COMPONENTS')])
    group('CONVICTION_BEHAVIOR_OVERRIDE','These latest inventory rules are referenced by SUSPECTED_CONVICTION; older 70% retention and 30% gross sell-value cap are superseded.',[(225,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE'),(226,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(227,'ONCHAIN_FRANK_BEHAVIOR','OLD_SELL_VALUE_VETO_EXPLICITLY_REMOVED'),(228,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE_50_PERCENT_OR_NET_BUYING'),(229,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE_35_PERCENT_DISTRIBUTION'),(230,'PRICE,EXECUTABILITY','REMOVED_NON_BEHAVIOR_AUTHORITY'),(231,'LIQUIDITY','REMOVED_NON_BEHAVIOR_AUTHORITY'),(232,'OTHER','NOT_FRANK_BEHAVIOR_EXCLUDED_FROM_TARGET_AUTHORITY'),(233,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(234,'OTHER','ASSET_SCOPE_NOT_FRANK_BEHAVIOR')])
    group('SUSPECTED_CONVICTION','Later-stage conjunction referencing persistence, T0 and latest inventory rules. Canonical says second Gmail; no numeric additional ADD count is specified.',[(310,'OTHER','OLD_STAGE_UPGRADE_CONTEXT'),(311,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE'),(312,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE'),(313,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(314,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE_UNQUANTIFIED_MATERIALITY'),(315,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE'),(316,'PRICE,EXECUTABILITY','REMOVED_NON_BEHAVIOR_AUTHORITY'),(317,'LIQUIDITY,OTHER','NOT_FRANK_BEHAVIOR_EXCLUDED_FROM_TARGET_AUTHORITY'),(318,'ONCHAIN_FRANK_BEHAVIOR','RETAIN_CANDIDATE'),(319,'OTHER','ASSET_SCOPE_NOT_FRANK_BEHAVIOR')])
    group('RESET_CANCELLATION_EXIT','Source behaviors are preserved; V1 episode reset/dust rules are not invented.',[(106,'OTHER','OLD_DELIVERED_STAGE_PREREQUISITE'),(109,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE'),(110,'ONCHAIN_FRANK_BEHAVIOR','UNQUANTIFIED_EFFECTIVE_CLOSE'),(111,'ONCHAIN_FRANK_BEHAVIOR','UNQUANTIFIED_DISTRIBUTION'),(112,'OTHER,LIQUIDITY','REMOVED_NON_BEHAVIOR_AUTHORITY'),(330,'OTHER','OLD_DELIVERED_STAGE_PREREQUISITE'),(331,'ONCHAIN_FRANK_BEHAVIOR,TIMING','RETAIN_CANDIDATE'),(332,'ONCHAIN_FRANK_BEHAVIOR','UNQUANTIFIED_EFFECTIVE_CLOSE'),(333,'LIQUIDITY','REMOVED_NON_BEHAVIOR_AUTHORITY'),(334,'OTHER','NOT_FRANK_BEHAVIOR_EXCLUDED_FROM_TARGET_AUTHORITY'),(335,'SOCIAL,ONCHAIN_FRANK_BEHAVIOR','SOCIAL_VETO_REMOVED_BEHAVIOR_UNQUANTIFIED'),(337,'TIMING','QUIET_SCAN_NOT_RESET'),(347,'OTHER','RETAIN_ONCE_PER_MINT_EPISODE_STAGE')])
    numbers=[['Path S single / aggregate / social lookback','>=5,000 USD / >=10,000 USD in 60 min / prior 2 h','NOT_MAPPED'],['Path C single','>=15,000 USD equivalent','NOT_ACCUMULATION_PROVENANCE_ONLY'],['Path C repeated','>=2 buys AND >=25,000 USD equivalent in 60 min','USER_SELECTED_V1_USDC_DIRECT'],['T0 path 1','>=2 buys AND >=3,000 USD equivalent in <=60 min','CONVICTION_CORE'],['T0 path 2','>=5,000 USD buy followed by >=1 additional buy within 60 min','CONVICTION_CORE'],['Persistence A','previous hourly WATCH; no numeric extra ADD requirement','CONVICTION_CORE'],['Persistence B','>=3 buys spanning >=45 min','CONVICTION_CORE'],['Conviction cumulative buy','>=10,000 USD equivalent per episode','CONVICTION_CORE'],['Inventory retention','normally >=50% of episode peak; OR resumed net buying in last 60 min and material open position','CONVICTION_CORE'],['Distribution veto / preconfirm cancellation','>35% token inventory fall in 60 min without re-accumulation','CONVICTION_CORE'],['Old FORMAL_EXIT reduction','>=35% tracked position reduction in rolling hour','OLD_EXIT_SCOPE'],['HFT count','>=3 active swaps in <=60 s for same mint','BEHAVIOR_VETO'],['HFT round trip','largely close inside ~20 min','APPROXIMATE_NOT_EXACT_THRESHOLD'],['Freshness target / stale boundary / refreshed buying','45–120 min / >3 h / active BUY within 60 min','TIMING'],['Deprecated executable price bounds','VWAP *0.92 to *1.10; stale-entry cap *1.05','REMOVED_FROM_AUTHORITY'],['Old preconfirm display deviations','>15%, >25% above VWAP','ENRICHMENT_ONLY'],['Superseded base entry rules','two consecutive hourly observations; >=70% retention; sell value <=30% gross buys','SUPERSEDED_BY_OVERRIDES'],['Old suggested sizing','10–30 USD base; 20–30 USD initial/add; 50–60 USD cap; 0–15 USD preconfirm; ~100 USD lane','NOT_SIGNAL_PREDICATES'],['Old runway scenarios','3x and 5x implied capitalization','NOT_SIGNAL_PREDICATES_NO_GUARANTEE'],['Old scheduler / overlap','hourly :29; 0–59 min latency; 15 min signature overlap; 2 h social overlap','OLD_OPERATIONAL_NOT_NEW_BEHAVIOR_THRESHOLD'],['Relative-size / percentile / dust / extra ADD count','NOT_SPECIFIED','DO_NOT_INVENT']]
    return {'policy_id':'FRANK_LOCAL_SIGNAL_V1','schema_version':1,'status':'FROZEN','enabled':True,'frozen':True,'provenance':['DERIVED_FROM_EXISTING_FRANK_BEHAVIOR_MODEL','NON_BEHAVIOR_VETO_GATES_REMOVED_BY_USER_REQUIREMENT'],'source':{'path':'crypto-300-profit-mission/state/frank-wallet-watch.md','commit':'f36432aec00c0d91078b120758556b7413775366','sha256':hashlib.sha256(raw).hexdigest(),'authority_reference':'crypto-300-profit-mission/AUTOMATION_RUNTIME.md Frank wallet conviction lane','precedence':'Two-stage 2026-09-29 04:20 override > latency-aware override > base rules'},'preconfirm_path_names':['S','C'],'preconfirm_path_a_exists':False,'preconfirm_path_b_exists':False,'groups':groups,'numbers':numbers,'mapping':{'FRANK_ACCUMULATION_SIGNAL':{'source':'PRECONFIRM_PATH_C_REPEATED_BRANCH','single_branch':'PATH_C_SINGLE_LARGE_BUY = NOT_ACCUMULATION','count_min':2,'window_seconds':3600,'quote_asset':'USDC','quote_quantity_min':'25000','hft_veto':False},'FRANK_MULTIPLE_SIGNAL':{'source':'SUSPECTED_CONVICTION_BEHAVIOR_CORE','requires_accumulation':True,'t0_repeated_buy_count':2,'t0_window_seconds':3600,'t0_repeated_amount_min':'3000','t0_large_buy_min':'5000','cumulative_amount_min':'10000','quote_asset':'USDC','persistence':{'A':'PRIOR_HOURLY_29_WATCH','B':{'buy_count_min':3,'buy_span_seconds_min':2700}},'retention_ratio_min':'0.50','net_buy_window_seconds':3600,'distribution_drop_ratio_gt':'0.35','distribution_window_seconds':3600,'hft_swaps_min':3,'hft_window_seconds':60,'rapid_roundtrip_reference_seconds':1200,'rapid_roundtrip_reference_is_approximate':True,'stale_after_seconds':10800,'fresh_buy_window_seconds':3600}},'amount_policy':{'usdc':'DIRECT_RAW_QUOTE_QUANTITY_NO_INDEPENDENT_USD_CLAIM','non_usdc_without_reliable_conversion':'UNDETERMINED','temporary_sol_conversion_allowed':False,'numeric_thresholds_preserved':['3000','5000','10000'],'unit_change_authorized_by':'USER_2026_10_04'},'observed_sequence_policy':{'lifetime_first_entry_required':False,'exact_zero_observed_active_inventory_closes_sequence':True,'unresolvable_sell':'INVENTORY_UNDETERMINED_NO_GUESSED_EXIT'},'unspecified':{'relative_buy_size_percentile':None,'additional_add_count':None,'reentry_requirement':None,'numeric_dust_close_threshold':None,'lifetime_zero_start_required':None,'material_open_position_numeric_definition':None,'reaccumulation_numeric_definition':None},'delivery_target':{'FRANK_ACCUMULATION_SIGNAL':['LOCAL'],'FRANK_MULTIPLE_SIGNAL':['LOCAL','STANDALONE_GMAIL'],'gpt_required':False,'historical_delivery_allowed':False},'production_trading':'NO_GO','other_persons':'DEFERRED','new_automation':False}

def main():
    policy=extract();JSON.write_text(json.dumps(policy,ensure_ascii=False,indent=2)+'\n');MARKDOWN.write_text(render(policy));print(json.dumps({'status':policy['status'],'enabled':policy['enabled'],'frozen':policy['frozen'],'predicate_count':sum(len(g['predicates']) for g in policy['groups']),'source_sha256':policy['source']['sha256']}))
if __name__=='__main__':main()
